services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:5.0
