apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  ports:
    - name: '3003'
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: payments
  type: ClusterIP
