apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: 265989594936.dkr.ecr.eu-west-1.amazonaws.com/auth:latest
          name: auth
          env:
            - name: HTTP_PORT
              value: '3001'
            - name: TCP_PORT
              value: '3002'
            - name: JWT_EXPIRATION_TIME
              value: '3600'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
            - name: MONGODB_URI
              value: mongodb+srv://zemfack:dDo5kIJf92HJ0y7a@sleepr.cjtx3vv.mongodb.net
          ports:
            - containerPort: 3001
            - containerPort: 3002
