apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: 265989594936.dkr.ecr.eu-west-1.amazonaws.com/reservations:latest
          name: reservations
          env:
            - name: PORT
              value: '3000'
            - name: AUTH_HOST
              value: auth
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3003'
            - name: MONGODB_URI
              value: 'mongodb://ngimdockzemfack:szJiZ1nBqSuXKc05@ac-ppube2q-shard-00-00.5jcz2wu.mongodb.net:27017,ac-ppube2q-shard-00-01.5jcz2wu.mongodb.net:27017,ac-ppube2q-shard-00-02.5jcz2wu.mongodb.net:27017/?ssl=true&replicaSet=atlas-6b15ir-shard-0&authSource=admin&retryWrites=true&w=majority'
          ports:
            - containerPort: 3000
